[build-system]
requires = [
    "setuptools>=61.2",
    "setuptools_scm[toml]>=3.4.3"
]
build-backend = "setuptools.build_meta"

[project]
name = "open-prime-rando-practice-mod"
description = "Provides prepared binaries of Practice Mod for use with open-prime-rando"
authors = [{name = "Henrique Gemignani"}]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
license = "GPL-3.0-or-later"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
]

# Entry Points for PyInstaller
[project.entry-points.pyinstaller40]
hook-dirs = "open_prime_rando_practice_mod.__pyinstaller:get_hook_dirs"

[tool.setuptools_scm]
local_scheme = "no-local-version"
write_to = "src/open_prime_rando_practice_mod/version.py"
scm.git.describe_command = "git describe --dirty --tags --long --match v[0-9]*"

[tool.ruff]
line-length = 120

extend-exclude = [
    "external/",
]
